homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.efrin, name='efrin'),
    path('organisasi-kepanitiaan/', views.orkep, name='orkep'),
    # dilanjutkan ...
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render

# Create your views here.
def efrin(request):
    return render(request, 'efrin.html')

def orkep(request):
    return render(request, 'organisasi-kepanitiaan.html')

homepage/templates/efrin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">

        <title>My Biodata</title>
    </head>
    <body style="background: url('/static/UI.jpeg'); background-size: cover;background-attachment: fixed;">
    <div class = "container" style="background-color: #8ee7b3ab; max-width: 800px;">
        <div class="row align-items-center justify-content-center">
            <div class="col-sm-12">
                <h1 align="center"> Siapa Sih Efrin? </h1>
                <hr align="center" width="50%" style="border: 5px dashed #555;">
                <h2 align="center"> Kenalan Yuk! </h2>
            </div>
            <div class="col-sm-12">
                <div class="container" style = "background-color: #d7e241;border-top: 4px solid black;border-bottom: 4px solid black;">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-sm-12 col-md-4">
                            <img src="{% static 'efrin.jpg' %}" width="200px" style="display: inline-flexbox;border-radius: 50%; border: 7px solid black;">
                        </div>
                        <div class="col-sm-12 col-md-8">
                            <table>
                                <tr><td><b>Nama</b></td> <td>:</td> <td>Sefrina Fauranisa</td></tr>
                                <tr><td><b>NPM</b></td> <td>:</td> <td>1906398944</td></tr>
                                <tr><td><b>Angkatan</b></td> <td>:</td> <td>2019</td></tr>
                                <tr><td><b>Hobi</b></td> <td>:</td> <td>Tidak pasti</td></tr>
                                <tr><td><b>Tempat Kuliah</b></td> <td>:</td> <td>Universitas Indonesia</td></tr>
                                <tr><td><b>Deskripsi Tentang Saya</b></td> <td>:</td> <td>Pemalas yang berpura-pura tidak malas</td></tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <table class="tables" >
                    <tr><th class="tables"><b>No.</b></th> 
                        <th class="tables"><b>Jenjang Pendidikan</b></th> 
                        <th class="tables"><b>Institusi Pendidikan</b></th>
                        <th class="tables"><b>Tahun</b></th>
                    </tr>
                    <tr>
                        <td class="tables">1</td>
                        <td class="tables">TK</td> 
                        <td class="tables">TK Bhakti Atomita</td> 
                        <td class="tables">2004-2007</td>
                    </tr>
                    <tr>
                        <td class="tables">2</td>
                        <td class="tables">SD</td> 
                        <td class="tables">SDN Batan Indah</td> 
                        <td class="tables">2007-2013</td>
                    </tr>
                    <tr>
                        <td class="tables">3</td>
                        <td class="tables">SMP</td> 
                        <td class="tables">SMPN 8 Tangerang Selatan</td> 
                        <td class="tables">2013-2016</td>
                    </tr>
                    <tr>
                        <td class="tables">4</td>
                        <td class="tables">SMA</td> 
                        <td class="tables">SMAN 2 Tangerang Selatan</td> 
                        <td class="tables">2016-2019</td>
                    </tr>
                    <tr>
                        <td class="tables">5</tb>
                        <td class="tables">UNIVERSITAS</td> 
                        <td class="tables">Universitas Indonesia</td> 
                        <td class="tables">2019-sekarang</td>
                    </tr>
                </table>
            </div>
            <div class="col-sm-8">
                <div class="container">
                    <div class="row justify-content-center align-items-center">
                        <div class="col-sm-12 col-md-6">
                            <div class="contacts">
                                <div class="judul1">
                                    <h2>Contact Me!</h2>
                                </div>
                                <div class="contents">
                                    <a href="https://www.instagram.com/efrinfrn/"><img src="{% static 'ig.png' %}" style="width:50px;height:50px;"></a>
                                    <a href="https://twitter.com/sefrina_efrin"><img src="{% static 'twt.png' %}" style="width:55px;height:55px;"></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-6">
                            <div class="more">
                                <div class="judul2">
                                    <h2>Want To Know More?</h2>
                                </div>
                                <div class="page1">
                                    <a href = "{% url 'homepage:orkep' %}"><h3 align = "center">Organisasi/Kepanitiaan</h3></a>
                                </div>
                            </div>
                        </div>
                    </div>  
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/organisasi-kepanitiaan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        
        <title>Organisasi-Kepanitiaan</title>

    </head>
<body style="background-color: #75c7f4;">
    <div class="container-fluid">
        <div class="container-fluid">
           <div class="row">
               <div class="col-sm-12 col-md-2">
                    <div class = "orkep">
                        <h3 align = "center">Organisasi/Kepanitiaan</h3>
                    </div>
                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="home">
                        <a href = "{% url 'homepage:efrin' %}"><h3 align = "center">Home</h3></a>
                    </div>
                </div>
            </div>
        </div>
        <div class = "container-fluid">
            <div class="row">
                <div class="col-sm-7 col-md-9">
                    <div class = "container-fluid" style="background-color:#8ee7b3ab; min-width: fit-content; height: 465px;">
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="tables">
                                    <tr><th class="tables"><b>No.</b></th> 
                                        <th class="tables"><b>Nama Organisasi</b></th> 
                                        <th class="tables"><b>Biro/ Departement</b></th>
                                        <th class="tables"><b>Tahun</b></th>
                                    </tr>
                                    <tr>
                                        <td class="tables">1</td>
                                        <td class="tables">BEM</td> 
                                        <td class="tables">Pengabdian Masyarakat</td> 
                                        <td class="tables">2020</td>
                                    </tr>
                                    <tr>
                                        <td class="tables">2</td>
                                        <td class="tables">FUKI</td> 
                                        <td class="tables">PSDM</td> 
                                        <td class="tables">2020</td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-sm-12">
                                <table class="tables">
                                    <tr><th class="tables"><b>No.</b></th> 
                                        <th class="tables"><b>Nama Kepanitiaan</b></th> 
                                        <th class="tables"><b>Tahun</b></th>
                                    </tr>
                                    <tr>
                                        <td class="tables">1</td>
                                        <td class="tables">Gelar Karya</td> 
                                        <td class="tables">2019</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">2</td>
                                        <td class="tables">Social Project PMB</td> 
                                        <td class="tables">2019</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">3</td>
                                        <td class="tables">BETIS</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">4</td>
                                        <td class="tables">WISGEN</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">5</tb>
                                        <td class="tables">SIWAK</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                    <tr>
                                        <td class="tables">6</tb>
                                        <td class="tables">MTQ UI</td> 
                                        <td class="tables">2020</td> 
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col sm-5 col-md-3">
                    <div class="vertical">
                        <div class="l3"></div>
                        <div class="l2"></div>
                        <div class="l1"></div>
                        <div class="l4"></div>
                        <div class="l5"></div>
                        <div class="l6"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<footer class="page-footer font-small unique-color-dark">
    <div style="background-color: #555;">
      <div class="container">
        <div class="row py-4 d-flex align-items-center">
          <div class="nama" style="background-color: #d7e241; border-radius: 100px;">
            <h6 class="mb-0">Efrin.frn</h6>
          </div>
        </div>
      </div>
      <div style="background-color: #E5E5E5;">
      <div class="container text-center text-md-left mt-5 ">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <h6 class="text-uppercase font-weight-bold">Deskripsi</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>Hai.</p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase font-weight-bold">Alamat</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>Kompleks Batan Indah blok M-41 RT 09 RW 04 Kademangan, Setu, Tangerang Selatan</p>
          </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase font-weight-bold">Contact</h6>
            <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
            <p>
              <i class="fas fa-home mr-3"></i>(021) 7561966</p>
            <p>
              <i class="fas fa-envelope mr-3"></i>fauranisasefrina@yahoo.com</p>
            <p>
              <i class="fas fa-phone mr-3"></i>fauranisasefrina@gmail.com</p>
            <p>
              <i class="fas fa-print mr-3"></i>sefrina.fauranisa@ui.ac.id</p>
          </div>
        </div>
      </div>
    </div>
  </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>